### ISSUE TITLE
The thread variable should be unset on process_response

### ISSUE THREAD

**Issue by kenjones21** [benrobster/django-threadlocals#9]
This is an issue specifically if one is doing something like unit tests, where the same thread will execute a request and then move on to do something else. The request object will linger, and it will appear as if there is still an active request when there isn't one.

**Comment by valentijnscholten** [comment]
Agree, this leaves variables behind in threads.

**Comment by benrobster** [comment]
Makes sense. Not set up to test this these days, but would be happy to merge a PR.
